info/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from. import views

app_name = 'info'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('resume/', views.resume, name='resume'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('contact/', views.contact, name='contact'),

] 
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls', namespace='info')),
]

info/models.py
from django.db import models
from phone_field import PhoneField
class About(models.Model):
    name = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250)
    job_role = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/%Y/%m/%d/')
    desc = models.TextField()
    birth_date = models.DateTimeField(auto_now=False, auto_now_add=False)
    phone_number = PhoneField(blank=True, help_text='Contact phone number')
    city = models.CharField(max_length=50)
    skills_desc = models.TextField()
    skill_one = models.CharField(max_length=50)
    skill_two = models.CharField(max_length=50)
    skill_three = models.CharField(max_length=50)
    skill_four = models.CharField(max_length=50)
    skill_five = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class School(models.Model):
    course = models.CharField(max_length=100)
    school = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250)
    start_year = models.DateTimeField(auto_now=False, auto_now_add=False)
    completion_year = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self) -> str:
        return self.course

class Job_Experience(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(max_length=250)
    start_year = models.DateTimeField(auto_now=False, auto_now_add=False)
    company = models.CharField(max_length=50)
    completion_year = models.DateTimeField(auto_now=False, auto_now_add=False)
    role_one = models.TextField()
    role_two = models.TextField()
    role_three = models.TextField()
    role_four = models.TextField()

    def __str__(self) -> str:
        return self.title

class Project(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=150)
    title = models.CharField(max_length=100)
    date_done = models.DateTimeField(auto_now_add=True)
    comment = models.TextField()
    def __str__(self) -> str:
        return self.name

info/views.py
from django.shortcuts import render
from .models import *

# Create your views here.
def home(request):
    banner = About.image
    context = {'banner': banner}
    return render(request, 'info/home.html', context)

def about(request):
    return render(request, 'info/about.html')

def resume(request):
    schools = School.objects.all()
    job_experiences = Job_Experience.objects.all()
    context = {'schools': schools, 'job_experiences': job_experiences}
    return render(request, 'info/resume.html', context)
    
def portfolio(request):
    projects = Project.objects.all()
    context = {'projects': projects}
    return render(request, 'info/portfolio.html', context)

def contact(request):
    return render(request, 'info/contact.html')

info/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link type='text/css' href="{% static "/css/style.css" %}" rel="stylesheet">

        {% bootstrap_css %}
        {% bootstrap_javascript jquery='full' %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/2.0.2/anime.min.js"></script>
   </head>
    <body>
        <div id="content">

        {% block content %}

        {% endblock %}
        {% include 'footer.html' %}
        </div>
        <script src="{% static '/js/app.js' %}"></script> 

    </body>
</html>

info/templates/footer.html
{% load static %}
<footer>
    <p>&copy; Copyrights Maina Munuhe</p>

</footer>

info/templates/info/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <!-- start section about us -->
  <div id="about" class="paddsection">
    <div class="container">
      <div class="row justify-content-between">

        <div class="col-lg-4 ">
          <div class="div-img-bg">
            <div class="about-img">
              <img src="{% static 'img/me.jpg'%}" class="img-responsive" alt="me">
            </div>
          </div>
        </div>

        <div class="col-lg-7">
          <div class="about-descr">

            <p class="p-heading">im a ux /ui designer austin based who loves clean, simple & unique design. i also enjoy crafting brand identities, icons, & ilustration work. </p>
            <p class="separator">To an English person, it will seem like simplified English, as a skeptical Cambridge friend of mine told me what Occidental is. The European languages are members of the same family.English person.</p>

          </div>

        </div>
      </div>
    </div>
  </div>
  <!-- end section about us -->
{% endblock content %}

info/templates/info/contact.html
{% extends 'base.html' %}
{% block content %}
 <!-- start section contact -->
<div id="contact" class="paddsection">
    <div class="container">
      <div class="contact-block1">
        <div class="row">

            <div class="col-lg-6">
                <div class="contact-contact">
                    <h2 class="mb-30">GET IN TOUCH</h2>
                    <ul class="contact-details">
                        <li><span>23 Main, Street</span></li>
                        <li><span>New York, United States</span></li>
                        <li><span>+88 01912704287</span></li>
                        <li><span>example@example.com</span></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-6">
                <form action="" method="post" role="form" class="contactForm">
                <div class="row">

                    <div id="sendmessage">Your message has been sent. Thank you!</div>
                    <div id="errormessage"></div>

                    <div class="col-lg-6">
                    <div class="form-group contact-block1">
                        <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                        <div class="validation"></div>
                    </div>
                    </div>

                    <div class="col-lg-6">
                    <div class="form-group">
                        <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                        <div class="validation"></div>
                    </div>
                    </div>

                    <div class="col-lg-12">
                    <div class="form-group">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                        <div class="validation"></div>
                    </div>
                    </div>

                    <div class="col-lg-12">
                    <div class="form-group">
                        <textarea class="form-control" name="message" rows="12" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                        <div class="validation"></div>
                    </div>
                    </div>

                    <div class="col-lg-12">
                    <input type="submit" class="btn btn-defeault btn-send" value="Send message">
                    </div>

                </div>
                </form>
            </div>
        </div>
      </div>
    </div>
</div>
{% endblock content %}

info/templates/info/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<div id='hero'>
    <div id='homepage'>
        <h1><span>Maina</span> Munuhe </h1>
        <h2>I'm a professional policy design and analysis consultant.</h2>
    </div>
</div>



{% endblock content %}

info/templates/info/portfolio.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'navbar.html' %}

<!-- start section portfolio -->
<div id="portfolio" class="text-center paddsection">

    <div class="container">
      <div class="row">
             {% for project in projects %}
          <div class="col-md-10">
               <h3 class="text-left">{{project.title}}</h3>
                <p class="text-left">{{ project.comment }}</p>
            <hr>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
   </div>

  </div>
  <!-- End section portfolio -->

  {% endblock content %}

info/templates/info/resume.html
{% extends 'base.html' %}
{% block content %}

<div class='resume'>
    <div class='banner'>
       <div class="main-row">
            <div>
              <br>
              <div class="resume-item">
                <h1 class='r-name'>Maina<br> Munuhe</h1>
                <h2>Expert Frontend developer and UX Engineer.</h2>
                <p>Engineer valued for driving high-performance accessible web experiences. I design quality, user-friendly and scalable products regardless of stack.</p>
                <hr>

                <h1 class="resume-title">Education</h1>
                    {% for ed in education %}
                    <div id='honors'>
                        <div class='details'>
                            <div class='m-details'>
                                <h4 class='hl'>{{ed.course}}</h4>
                                <div class='years'>
                                    <h5>{{ed.start_year|date:'Y'}} - {{ed.completion_year|date:'Y'}}</h5>
                                </div>
                            </div>
                            <p><em>{{ed.school }}</em></p>
                       </div>
                    </div>
                     {% endfor %}
                </div>
                <hr>
            </div>
            <div>
                <div class="resume-item">
                    <h3 class="resume-title">Professional Experience</h3>

                    {% for work in work %}
                    <div id='honors'>

                        
                        <div class='details'>
                            <div class='m-details'>
                                <h4>{{work.title}}</h4>
                                <div class='years'>
                                    <h5>{{work.start_year|date:'Y'}} - {{work.completion_year|date:'Y'}}</h5>
        
                                </div>
                            </div>

                                <p><em>{{work.company}}</em></p>
                                <p></p>
                                <ul>
                                    <li>{{work.role_one}}</li>
                                    <li>{{work.role_two}}</li>
                                    <li>{{work.role_three}}</li>
                                    <li>{{work.role_four}}</li>
                                </ul>
                        </div>
                    </div>
                    {% endfor %}
                <br>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

info/templates/navbar.html
{% load static %}

<nav id='navbar' class="navbar navbar-expand-lg navbar-light" style="background: transparent;

height: 20vh; z-index: 997; width: 87vw; margin: auto;
">
<h1 id='logo'>
  <a href="/"class='logo'>M&M</a>

</h1>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border:none;">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
      <li class="nav-item">
          <a class="nav-link" target='_blank' href="{% url 'info:resume'%}">Resume</a>
        </li> 
        <li class="nav-item">
          <a class="nav-link" href="{% url 'info:portfolio'%}">Work</a>
        </li>
     </ul>
   </div>
  </nav>